spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:demo_park;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=com.mballem.demoparkapi.web.controller

spring.messages.basename=messages
spring.messages.encoding=UTF-8

app.seed.enabled=true

server.port=${PORT:8080}
