# LOCALE
spring.web.locale-resolver=fixed
spring.web.locale=pt_BR

# H2 Database Connection Properties (Em Memoria)
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:demo_park;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Springdoc OpenApi 3.1 & Swagger 3
springdoc.swagger-ui.path=/docs-park.html
springdoc.api-docs.path=/docs-park
springdoc.packagesToScan=com.mballem.demoparkapi.web.controller

# MESSAGES i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true