name: park_app
description: "Aplicativo do ParkAPI: solicitação de vagas com QR Code e painel administrativo."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  intl: ^0.20.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.4.2
  printing: ^5.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
